# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_source_sink_linking.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SourceSinkLinking(object):
    def setupUi(self, SourceSinkLinking):
        SourceSinkLinking.setObjectName("SourceSinkLinking")
        SourceSinkLinking.resize(1072, 331)
        self.gridLayoutWidget = QtWidgets.QWidget(SourceSinkLinking)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 981, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listSource = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listSource.setObjectName("listSource")
        self.gridLayout.addWidget(self.listSource, 1, 1, 1, 1)
        self.labelRight = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRight.setObjectName("labelRight")
        self.gridLayout.addWidget(self.labelRight, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushAccept = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushAccept.sizePolicy().hasHeightForWidth())
        self.pushAccept.setSizePolicy(sizePolicy)
        self.pushAccept.setMinimumSize(QtCore.QSize(52, 52))
        self.pushAccept.setObjectName("pushAccept")
        self.verticalLayout.addWidget(self.pushAccept)
        self.pushReset = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushReset.sizePolicy().hasHeightForWidth())
        self.pushReset.setSizePolicy(sizePolicy)
        self.pushReset.setMinimumSize(QtCore.QSize(52, 52))
        self.pushReset.setObjectName("pushReset")
        self.verticalLayout.addWidget(self.pushReset)
        self.pushExit = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushExit.sizePolicy().hasHeightForWidth())
        self.pushExit.setSizePolicy(sizePolicy)
        self.pushExit.setMinimumSize(QtCore.QSize(52, 52))
        self.pushExit.setObjectName("pushExit")
        self.verticalLayout.addWidget(self.pushExit)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.labelLeft = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLeft.setObjectName("labelLeft")
        self.gridLayout.addWidget(self.labelLeft, 0, 1, 1, 1)
        self.listWidgetExisting = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidgetExisting.setObjectName("listWidgetExisting")
        self.gridLayout.addWidget(self.listWidgetExisting, 1, 3, 1, 1)
        self.labelExisting = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelExisting.setAlignment(QtCore.Qt.AlignCenter)
        self.labelExisting.setObjectName("labelExisting")
        self.gridLayout.addWidget(self.labelExisting, 0, 3, 1, 1)
        self.listSink = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listSink.setObjectName("listSink")
        self.gridLayout.addWidget(self.listSink, 1, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushDelete = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDelete.sizePolicy().hasHeightForWidth())
        self.pushDelete.setSizePolicy(sizePolicy)
        self.pushDelete.setMinimumSize(QtCore.QSize(52, 52))
        self.pushDelete.setObjectName("pushDelete")
        self.verticalLayout_2.addWidget(self.pushDelete)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 4, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 5)
        self.gridLayout.setColumnStretch(3, 10)
        self.gridLayout.setColumnStretch(4, 2)

        self.retranslateUi(SourceSinkLinking)
        QtCore.QMetaObject.connectSlotsByName(SourceSinkLinking)

    def retranslateUi(self, SourceSinkLinking):
        _translate = QtCore.QCoreApplication.translate
        SourceSinkLinking.setWindowTitle(_translate("SourceSinkLinking", "Form"))
        self.labelRight.setText(_translate("SourceSinkLinking", "sink"))
        self.pushAccept.setText(_translate("SourceSinkLinking", "accept"))
        self.pushReset.setText(_translate("SourceSinkLinking", "reset"))
        self.pushExit.setText(_translate("SourceSinkLinking", "reject"))
        self.labelLeft.setText(_translate("SourceSinkLinking", "source"))
        self.labelExisting.setText(_translate("SourceSinkLinking", "existing"))
        self.pushDelete.setText(_translate("SourceSinkLinking", "delete"))
