# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assign_equations_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 844)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(100, 0))
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.ForceTabbedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 681, 741))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_node = QtWidgets.QWidget()
        self.tab_node.setObjectName("tab_node")
        self.frameNodeTop = QtWidgets.QFrame(self.tab_node)
        self.frameNodeTop.setGeometry(QtCore.QRect(20, 100, 641, 281))
        self.frameNodeTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameNodeTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNodeTop.setObjectName("frameNodeTop")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frameNodeTop)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutNodeTop = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutNodeTop.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutNodeTop.setObjectName("verticalLayoutNodeTop")
        self.frameNodeBottom = QtWidgets.QFrame(self.tab_node)
        self.frameNodeBottom.setGeometry(QtCore.QRect(20, 410, 641, 281))
        self.frameNodeBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameNodeBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNodeBottom.setObjectName("frameNodeBottom")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frameNodeBottom)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 621, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayoutNodeBottom = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayoutNodeBottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutNodeBottom.setObjectName("verticalLayoutNodeBottom")
        self.comboNodeNetworks = QtWidgets.QComboBox(self.tab_node)
        self.comboNodeNetworks.setGeometry(QtCore.QRect(20, 40, 251, 25))
        self.comboNodeNetworks.setObjectName("comboNodeNetworks")
        self.pushGraphNode = QtWidgets.QPushButton(self.tab_node)
        self.pushGraphNode.setGeometry(QtCore.QRect(340, 24, 76, 51))
        self.pushGraphNode.setText("")
        self.pushGraphNode.setObjectName("pushGraphNode")
        self.tabWidget.addTab(self.tab_node, "")
        self.tab_arc = QtWidgets.QWidget()
        self.tab_arc.setObjectName("tab_arc")
        self.frameArcTop = QtWidgets.QFrame(self.tab_arc)
        self.frameArcTop.setGeometry(QtCore.QRect(20, 100, 641, 281))
        self.frameArcTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameArcTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameArcTop.setObjectName("frameArcTop")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.frameArcTop)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 10, 621, 261))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayoutArcTop = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayoutArcTop.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutArcTop.setObjectName("verticalLayoutArcTop")
        self.frameArcBottom = QtWidgets.QFrame(self.tab_arc)
        self.frameArcBottom.setGeometry(QtCore.QRect(20, 410, 641, 281))
        self.frameArcBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameArcBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameArcBottom.setObjectName("frameArcBottom")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frameArcBottom)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 621, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayoutArcBottom = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayoutArcBottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutArcBottom.setObjectName("verticalLayoutArcBottom")
        self.comboArcNetworks = QtWidgets.QComboBox(self.tab_arc)
        self.comboArcNetworks.setGeometry(QtCore.QRect(20, 40, 252, 25))
        self.comboArcNetworks.setObjectName("comboArcNetworks")
        self.tabWidget.addTab(self.tab_arc, "")
        self.tab_intraface = QtWidgets.QWidget()
        self.tab_intraface.setObjectName("tab_intraface")
        self.frameIntraTop = QtWidgets.QFrame(self.tab_intraface)
        self.frameIntraTop.setGeometry(QtCore.QRect(20, 100, 641, 281))
        self.frameIntraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIntraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIntraTop.setObjectName("frameIntraTop")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frameIntraTop)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 621, 261))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayoutIntraTop = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayoutIntraTop.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutIntraTop.setObjectName("verticalLayoutIntraTop")
        self.frameIntraBottom = QtWidgets.QFrame(self.tab_intraface)
        self.frameIntraBottom.setGeometry(QtCore.QRect(20, 410, 641, 281))
        self.frameIntraBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIntraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIntraBottom.setObjectName("frameIntraBottom")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frameIntraBottom)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 621, 261))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayoutIntraBottom = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayoutIntraBottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutIntraBottom.setObjectName("verticalLayoutIntraBottom")
        self.tabWidget.addTab(self.tab_intraface, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(530, 10, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushSave.setText("")
        self.pushSave.setObjectName("pushSave")
        self.horizontalLayout_2.addWidget(self.pushSave)
        self.pushInfo = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushInfo.setText("")
        self.pushInfo.setObjectName("pushInfo")
        self.horizontalLayout_2.addWidget(self.pushInfo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Process Modeller"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_node), _translate("MainWindow", "node"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_arc), _translate("MainWindow", "arc"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_intraface), _translate("MainWindow", "intraface"))
