# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_equations.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(978, 589)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        Form.setFont(font)
        Form.setToolTip("")
        self.groupEquationEditor = QtWidgets.QGroupBox(Form)
        self.groupEquationEditor.setGeometry(QtCore.QRect(10, 110, 951, 321))
        self.groupEquationEditor.setObjectName("groupEquationEditor")
        self.lineNewVariable = QtWidgets.QLineEdit(self.groupEquationEditor)
        self.lineNewVariable.setGeometry(QtCore.QRect(11, 50, 181, 27))
        self.lineNewVariable.setObjectName("lineNewVariable")
        self.layoutWidget = QtWidgets.QWidget(self.groupEquationEditor)
        self.layoutWidget.setGeometry(QtCore.QRect(430, 0, 178, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushAccept = QtWidgets.QPushButton(self.layoutWidget)
        self.pushAccept.setMinimumSize(QtCore.QSize(85, 0))
        self.pushAccept.setMaximumSize(QtCore.QSize(85, 16777215))
        self.pushAccept.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color :rgb(255, 255, 255)")
        self.pushAccept.setText("")
        self.pushAccept.setObjectName("pushAccept")
        self.horizontalLayout_2.addWidget(self.pushAccept)
        self.pushDeleteEquation = QtWidgets.QPushButton(self.layoutWidget)
        self.pushDeleteEquation.setMinimumSize(QtCore.QSize(85, 0))
        self.pushDeleteEquation.setMaximumSize(QtCore.QSize(85, 16777215))
        self.pushDeleteEquation.setStyleSheet("background-color: rgb(255, 17, 0);\n"
"color:rgb(255, 255, 255)")
        self.pushDeleteEquation.setText("")
        self.pushDeleteEquation.setObjectName("pushDeleteEquation")
        self.horizontalLayout_2.addWidget(self.pushDeleteEquation)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupEquationEditor)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 90, 941, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.lineExpression = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineExpression.setFont(font)
        self.lineExpression.setObjectName("lineExpression")
        self.horizontalLayout_5.addWidget(self.lineExpression)
        self.labelQuestion = QtWidgets.QLabel(Form)
        self.labelQuestion.setGeometry(QtCore.QRect(1080, -470, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.labelQuestion.setFont(font)
        self.labelQuestion.setAutoFillBackground(False)
        self.labelQuestion.setStyleSheet("background-color: rgb(255, 17, 0);")
        self.labelQuestion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQuestion.setObjectName("labelQuestion")
        self.labelNetwork = QtWidgets.QLabel(Form)
        self.labelNetwork.setGeometry(QtCore.QRect(20, 10, 741, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelNetwork.setFont(font)
        self.labelNetwork.setObjectName("labelNetwork")
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 450, 941, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setStyleSheet("background-color: rgb(148, 148, 56);\n"
"color :rgb(255, 255, 255)")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pushPickVariables = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushPickVariables.setObjectName("pushPickVariables")
        self.horizontalLayout_3.addWidget(self.pushPickVariables)
        self.pushPickIndices = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushPickIndices.setObjectName("pushPickIndices")
        self.horizontalLayout_3.addWidget(self.pushPickIndices)
        self.pushPickOperations = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushPickOperations.setObjectName("pushPickOperations")
        self.horizontalLayout_3.addWidget(self.pushPickOperations)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushCancel = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushCancel.setText("")
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout.addWidget(self.pushCancel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.lineDocumentation = QtWidgets.QLineEdit(Form)
        self.lineDocumentation.setGeometry(QtCore.QRect(20, 390, 941, 27))
        self.lineDocumentation.setText("")
        self.lineDocumentation.setObjectName("lineDocumentation")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 250, 941, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget.raise_()
        self.labelNetwork.raise_()
        self.groupEquationEditor.raise_()
        self.labelQuestion.raise_()
        self.lineDocumentation.raise_()
        self.textBrowser.raise_()

        self.retranslateUi(Form)
        self.lineNewVariable.editingFinished.connect(self.lineExpression.setFocus)
        self.lineExpression.editingFinished.connect(self.lineDocumentation.setFocus)
        self.lineDocumentation.editingFinished.connect(self.lineExpression.setFocus)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupEquationEditor.setToolTip(_translate("Form", "Equation editor"))
        self.groupEquationEditor.setTitle(_translate("Form", "Equation Editor:  Variable := Expression"))
        self.lineNewVariable.setToolTip(_translate("Form", "variable field"))
        self.pushAccept.setToolTip(_translate("Form", "puts things in place and closes equation editor"))
        self.label.setText(_translate("Form", ":="))
        self.lineExpression.setToolTip(_translate("Form", "equation editor field -- press return when finished"))
        self.labelQuestion.setToolTip(_translate("Form", "Variable equation editor\n"
"Generates new variables and equations\n"
"Resulting bipartite graph (variable|equation) must be complete before ontology can be used\n"
"predefined variables: t, dt, t0"))
        self.labelQuestion.setText(_translate("Form", "?"))
        self.labelNetwork.setText(_translate("Form", "TextLabel"))
        self.label_2.setToolTip(_translate("Form", "Pick tables"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">  pick tables  </span></p></body></html>"))
        self.pushPickVariables.setToolTip(_translate("Form", "pick variable table"))
        self.pushPickVariables.setText(_translate("Form", "variables"))
        self.pushPickIndices.setToolTip(_translate("Form", "pick index table"))
        self.pushPickIndices.setText(_translate("Form", "indices"))
        self.pushPickOperations.setToolTip(_translate("Form", "pick operations"))
        self.pushPickOperations.setText(_translate("Form", "operations"))
        self.pushCancel.setToolTip(_translate("Form", "reset closes equation editor clears alias table"))
        self.lineDocumentation.setPlaceholderText(_translate("Form", "describe equation"))
